### ISSUE TITLE
Usage of period in toml (upload.format) causing toml parser error

### ISSUE THREAD

**Issue by jacob-8** [cloudflare/cloudflare-docs#1182]
### Expected Behavior
I upgraded to the most recent wrangler version and expected adding `upload.format = "service-worker"` to the toml file to just work as described in https://developers.cloudflare.com/workers/cli-wrangler/configuration#service-workers 

### Actual Behavior
When parsing it with the [toml](https://www.npmjs.com/package/toml) package it throws: 
`Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.`

### Section that requires update
Should be written in similar fashion as done in the [ES Modules section](https://developers.cloudflare.com/workers/cli-wrangler/configuration#es-modules):
```
[build.upload]
format = "service-worker"
```

### Additional information
Ran into this error when running `npm run build` in a SvelteKit project that uses `@sveltejs/adapter-cloudflare-workers` - see https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare-workers/index.js#L59L61.

**Comment by kristianfreeman** [comment]
cc @cloudflare/wrangler team to double check this syntax

**Comment by nilslice** [comment]
@jwrunner - which version of `wrangler` are you using? 

```bash
wrangler --version
```

This syntax should not be causing any issues, taking this manifest file for example: 

```toml
name = "upload-format"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
```

Testing on latest release, `v1.16.1`

**Comment by nilslice** [comment]
Oh, my bad I misread the initial issue. 

Testing on latest `wrangler@v1.16.1` and both syntax variants work:

```toml
[build.upload]
format = "service-worker"
```

```toml
[build]
command = "npm install && npm run build"
upload.format = "service-worker"
```

--- 

`wrangler` uses [this crate](https://crates.io/crates/toml) to parse the `wrangler.toml` file. You linked to an `npm` package - are you trying to parse the TOML from a separate program?
