### ISSUE TITLE
[Hyperdrive] Documentation for hyperdrive - pg client initialisation fails

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/cloudflare-docs#13661]
### Existing documentation URL(s)

- https://developers.cloudflare.com/hyperdrive/examples/cockroachdb/

### What changes are you suggesting?

I followed the code example but I am getting the below error when initializing the pg Client.

```
TypeError: r is not a constructor
    at Cg.exports.getStream (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:24410:22)
    at new Ag (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:24424:63)
    at new vh (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:24843:278)
    at Object.example (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:29731:21)
    at n.resolve (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:29123:23)
    at qS (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:6829:101)
    at _f (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:6810:60)
    at KV (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:6793:24)
    at jS (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:6745:45)
    at nA (file:///Users/mf/Projects/streamscore/.wrangler/tmp/dev-kgPsYv/index.js:29222:58) {
  stack: TypeError: r is not a constructor
    at Cg.export…score/.wrangler/tmp/dev-kgPsYv/index.js:29222:58),
  message: r is not a constructor
}
```

This is my wrangler toml:

```toml
name = "worker-apollo-server-local"
main = "build/index.js"
workers_dev = true
compatibility_date = "2023-09-11"
node_compat = true # required for database drivers to function

[build]
command = "npm run generate && npm run build"

[vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = ""

[env.production]
name = "worker-apollo-server"

[[env.production.kv_namespaces]]
binding = "GRAPHQL_CACHE"
id = "XXX"

[env.production.vars]
GRAPHQL_BASE_ENDPOINT = "/"
GRAPHQL_KV_CACHE = "true"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "XXXX"
localConnectionString="ANY_VALUE"
```

Any my code:

```ts
import { Resolvers } from "./@types/schema.generated";
import { Client } from "pg";

const resolvers: Resolvers<ApolloContext> = {
  Query: {
    example: async () => {
      // Create a database client that connects to our database via Hyperdrive
      // Hyperdrive generates a unique connection string you can pass to
      // supported drivers, including node-postgres, Postgres.js, and the many
      // ORMs and query builders that use these drivers.

      try {
        const client = new Client({ // <!----- this line fails
          connectionString: HYPERDRIVE.connectionString,
        });

        // Connect to our database
        await client.connect();

        // Test query
        const result = await client.query({ text: "SELECT * FROM pg_tables" });

        // Returns result rows as JSON
        return "hi world";
      } catch (e) {
        console.log(e);
        return e as string;
      }

      return "Hello universe!";
    },

    pokemon: (_source: any, { id }: any, { dataSources }: any) => {
      return dataSources.pokemonAPI.getPokemon(id);
    },
  },
};

export default resolvers;
```

Based on this skeleton repo: https://github.com/kimyvgy/worker-apollo-server-template
