### ISSUE TITLE
[Workers] Update TOML formatting on "Configure wrangler.toml" page

### ISSUE THREAD

**Issue by timabb031** [cloudflare/cloudflare-docs#4695]
### Which Cloudflare product does this pertain to?

Workers

### Existing documentation URL(s)

https://developers.cloudflare.com/workers/wrangler/configuration/

### Section that requires update

kv_namespaces
durable_objects
r2_buckets
services

### What needs to change?

The config sections for kv_namespaces, durable_objects, r2_buckets and services aren't actually valid TOML due to the way they've been formatted (which I appreciate is for reference/explanatory purposes). If a user copy/pastes one of those examples into their wrangler.toml file they might it expect it to work when they run `wrangler dev` but it won't until it's reformatted.

For example, if I copy the `kv_namespaces` section into my wrangler.toml file, edit the `binding`/`id` vars and then run `wrangler dev` it shows "ERROR - Unterminated inline array". Pasting that bit of config into an online TOML parser also shows a validation error.

### How should it change?

It might be worth considering moving the key comments up a level and reformatting the relevant sections to be valid TOML.

e.g.

```
# ...
# binding - The binding name used to refer to the KV namespace
# id - The ID of the KV namespace at the edge
# preview_id - The ID of the KV namespace used during `wrangler dev`
kv_namespaces = [
  { binding = "TEST_NAMESPACE", id = "", preview_id = "" }
]
```

I realise this might not be quite as clear as it is now, but given that TOML isn't a widely known format, I think that a lot of users who copy/paste config from this page won't initially realise that it need to be reformatted for the config to be valid and then have to spend time figuring out how it should be formatted.

### Additional information

![image](https://user-images.githubusercontent.com/51492403/171997812-ac3b5d58-1223-4f6e-b8e9-38e39fc6d312.png)

**Comment by KianNH** [comment]
It looks like there's two options.

A) Fix the existing example to be proper inline tables - the 'object' contained within `{}` must be on the same line

```toml
r2_buckets  = [
	{ binding = "TEST_BUCKET", bucket_name = "", preview_bucket_name =  "" },
	{ binding = "TEST_BUCKET", bucket_name = "", preview_bucket_name =  "" }
]
```

B) Move to the array of tables format - as suggested by @gkocyigit

```toml
[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
preview_bucket_name =  "<YOUR_TEST_BUCKET_NAME>"

[[r2_buckets]]
binding = 'MY_BUCKET' # <~ valid JavaScript variable name
bucket_name = '<YOUR_BUCKET_NAME>'
preview_bucket_name =  "<YOUR_TEST_BUCKET_NAME>"
```

@jkup @deadlypants1973 which would be best?

Personally the array of tables one suggested in #4699 seems like it'd be easier to maintain the existing comments & seems to be the 'newer' style.
