### ISSUE TITLE
Documentation does not mention, are account_id and zone_id secret or not

### ISSUE THREAD

**Issue by revelt** [cloudflare/cloudflare-docs#474]
https://developers.cloudflare.com/workers/cli-wrangler/authentication page doesn't mention, do `account_id` and `zone_id` need to be kept secret or not. 

I assumed they all should be kept **secret** and encountered some problems. Sourcehut CI can [secretly](https://man.sr.ht/builds.sr.ht/#secrets) write an arbitrary file to an arbitrary location during the CI bootstrap, so I thought let's recreate `.wrangler/config/default.toml` with all the secrets, then `wrangler` will detect them. Apparently, not.

`.wrangler/config/default.toml`:

```
api_token = "<redacted>"
account_id = "<redacted>"
zone_id = "<redacted>"
```

and `wrangler.toml`:

```toml
# name of your Worker script
name = "<redacted>"

# api_token (env var CF_API_TOKEN) - set by Sourcehut CI writing .wrangler/config/default.toml
# account_id (env var CF_ACCOUNT_ID) - same
# zone_id (env var CF_ZONE_ID) - same

# Specifies how wrangler build will build your project
# webpack|javascript|rust
type = "webpack"

#worker will be deployed to your workers.dev
workers_dev = true
route = "<redacted>.com/*"

[site]
bucket = "./build"
entry-point = "workers-site"
```

The build failed because `wrangler` complained:

```
Error: field `account_id` is required to deploy to workers.dev
```

I'm wary to commit `account_id` and `zone_id` in a publicly-facing `wrangler.toml`. It would be nice to add some reassurance to the documentation, especially, https://developers.cloudflare.com/workers/cli-wrangler/authentication page — are these two variables, `account_id` and `zone_id` public or secret.

Also, Sourcehut CI doesn't allow to programmatically set an arbitrary global secret env vars (like Gitlab does); we can't do:

```
CF_ACCOUNT_ID=accountID CF_API_TOKEN=veryLongAPIToken wrangler publish
```

Please consider updating https://developers.cloudflare.com/workers/cli-wrangler/authentication page to mention `account_id` and `zone_id` privacy.
