### ISSUE TITLE
Copy button has a broken styling on Firefox

### ISSUE THREAD

**Issue by arata-ae** [cloudflare/cloudflare-docs#6852]
### Example URL(s)

https://developers.cloudflare.com/workers/get-started/quickstarts

### Actual Behavior

![スクリーンショット 2022-11-28 11 38 08](https://user-images.githubusercontent.com/101444904/204195311-27e77aeb-e5f8-407d-afc2-8bb2d968b64e.jpg)

As shown on the screenshot, the copy button has an unexpected word break on Firefox (v107), but it's fine on Chromium. Upon a quick investigation, this is caused by the following CSS:

```css
.WorkerStarter--command {
  --copy-button-width: 4rem;
}
.WorkerStarter--command-copy-button-wrapper {
  width: calc(var(--copy-button-width) - 2px);
}
```

I didn't go deep enough to find out where the magic number comes from (2px), but I found that the value should have been 1.67px or smaller. Removing the subtraction, or the entire width declaration appears to work also (on this specific page, I haven't tested other pages).

### Expected Behavior

The text "Copy" on the button should be styled on a single line.
